# Generated by Django 4.0.5 on 2022-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('foto', models.FileField(upload_to='foto')),
                ('service', models.CharField(max_length=255)),
                ('more_service', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
